site_name: '发布平台-工单系统'
site_description: '这是一个工单系统的Demo'

nav:
  - '概览': 'overview.md'

  - '部署':
      - '部署 jira-servicedesk': 'jira_servicedesk.md'
      - '部署 jenkins': 'jenkins.md'
      - '部署 ansible': 'ansible.md'
      - '部署 awx': 'ansible.md'
      - '部署 minio': 'minio.md'

  - 'Demo 演示':
      - 'Mysql 演示': 'mysql.md'
      - 'Zabbix 演示': 'zabbix.md'


theme: material
#  feature:
#    tabs: true

extra_css:
  - 'css/custom.css'

plugins:
  - search

markdown_extensions:
  - codehilite
  - footnotes
  - admonition
  - toc:
      permalink: true