site_name: 发布平台-工单系统Demo
site_description: 发布平台-工单系统Demo

nav:
  - '部署文档':
      - '概述': index.md
      - '部署':
          - 'install jira-servicedesk': 'install.md'
          - 'install ansible-awx': 'install.md'
          - 'install jenkins': 'install.md'
          - 'install minio': 'install.md'
      - '演示Demo':
          - '前端工程一览': 'overview.md'
          - '管理后台':
              - '前端': 'overview.md'
      - '部署服务': 'overview.md'
      - '验证部署': 'overview.md'
      - '监控': 'overview.md'

theme: material
#  feature:
#    tabs: true

extra_css:
  - 'css/custom.css'

plugins:
  - search

markdown_extensions:
  - codehilite
  - footnotes
  - admonition
  - toc:
      permalink: true